name: template
description: A template Flutter Project
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  bloc: ^8.1.0
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.7
  flutter_screenutil: ^5.5.3+2
  formz: ^0.6.0
  freezed_annotation: ^2.2.0
  go_router: ^8.0.5
  google_fonts: ^5.1.0
  injectable: ^2.1.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  shared_preferences: ^2.0.15
  uuid: ^3.0.6
  
dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.4.5
  flutter_gen_runner: ^5.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  get_it: ^7.2.0
  injectable_generator: ^2.1.3
  json_serializable: ^6.7.0
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0+1

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    # flare_flutter: true
    # rive: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/
